###
### VARIABLES
###

@baseUrl = http://localhost:8000
@token = {{login.response.body.token}}
@email = test05@gmail.fr
@password = Test62200
@alertId = 61c0f70649023f0fbf8b45b5


###
### USERS
###

### Signup
POST {{baseUrl}}/api/users/signup HTTP/1.1
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "firstname": "Pat",
  "lastname": "Hibulaire",
  "address": "42 rue nullepart ailleurs",
  "phone": "0123456789",
  "city": "Calais",
  "postCode": "62200"
}

### Login
# @name login
POST {{baseUrl}}/api/users/login HTTP/1.1
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


###
### Alert
### Authorization: Bearer {{token}}

### Create: Envoie d'une alerte?token={{token}}
POST {{baseUrl}}/api/alerts?token={{token}} HTTP/1.1
Content-Type: application/json

{
  "type": "voirie",
  "description": "Mon voisin est un con 2 !",
  "address": "Mars"
}

### Read All: Liste toute les alertes
GET {{baseUrl}}/api/alerts?token={{token}}

### Read: Affiche une alerte
GET {{baseUrl}}/api/alerts/{{alertId}}?token={{token}}

### Update: Modifie une alerte
# PATCH {{baseUrl}}/api/alerts/{{alertId}} HTTP/1.1
# content-type: application/json

# {
#   "name": "Suite dans les idées",
#   "maxPersons": 69
# }

### Delete: Efface une chambre
# DELETE {{baseUrl}}/api/alerts/{{alertId}} HTTP/1.1
# Content-Type: application/json
