###
### Test de l'API avec l'extension « REST Client » de Visual Studio Code
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###
###

###
### VARIABLES
###

@baseUrl = http://localhost:8000
@token = {{login.response.body.token}}
@userId = ''
@email = test342@gmail.fr
@password = Test62200
@alertId = 61c0f70649023f0fbf8b45b5


###
### Citoyen
###

### Signup
POST {{baseUrl}}/api/users/signup HTTP/1.1
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "firstname": "Pat",
  "lastname": "Hibulaire",
  "address": "42 rue nullepart ailleurs",
  "phone": "0123456789",
  "city": "Calais",
  "postCode": "62200"
}

### Login
# @name login
POST {{baseUrl}}/api/users/login HTTP/1.1
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
### Citoyen Connecté
###

### Affiche le profil du Citoyen
GET {{baseUrl}}/api/users/account HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Mise à jour du profil du Citoyen
PATCH {{baseUrl}}/api/users/account HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "firstname": "David",
  "lastname": "Vincent"
}

### Supprime le profil du Citoyen
DELETE {{baseUrl}}/api/users/account HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Create: Envoie d'une alerte
POST {{baseUrl}}/api/alerts HTTP/1.1
Content-Type: multipart/form-data; boundary=---border
Authorization: Bearer {{token}}

---border
Content-Disposition: form-data; name="body"
Content-Type: application/json

{
  "typeAlert": "voirie",
  "description": "Mon voisin est un con finis !",
  "addressAlert": "Mars"
}

---border
Content-Disposition: form-data; name="photo"; filename="imageTest.jpg"
Content-Type: image/jpg

< ../imageTest.jpg
---border

### Read All: Liste toute les alertes
GET {{baseUrl}}/api/alerts/list
Content-Type: application/json
Authorization: Bearer {{token}}

### Read: Affiche l'alerte :alertId
GET {{baseUrl}}/api/alerts/{{alertId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Delete: Efface l'alerte :alertId
DELETE {{baseUrl}}/api/alerts/{{alertId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
### Responsable
###

### Patch: Mise à jour du status de l'alerte
PATCH {{baseUrl}}/api/alerts/{{{userId}}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "doing"
}

###
### Admin
###

### ReadOne: Affiche l'utilisateur :userId
GET {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### ReadAll: Affiche tous les utilisateurs
GET {{baseUrl}}/api/users/list
Content-Type: application/json
Authorization: Bearer {{token}}

### Update: Modifie l'utilisateur :userId
PATCH {{baseUrl}}/api/users/{{userId}} HTTP/1.1
content-type: application/json

{
  "firstname": "Donald",
  "lastname": "Duck"
}
