version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - cityalert-mongodb:/data/db
    command: mongod
    networks:
      - cityalert

volumes:
  cityalert-mongodb: {}

networks:
  cityalert:
